# Generated by Django 4.2.23 on 2025-08-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FXChainTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this template (e.g., 'Warm Vocal Chain')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this template is good for",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("hip-hop", "Hip-Hop"),
                            ("edm", "EDM"),
                            ("rock", "Rock"),
                            ("pop", "Pop"),
                            ("rnb", "R&B"),
                            ("jazz", "Jazz"),
                            ("country", "Country"),
                            ("reggae", "Reggae"),
                            ("ambient", "Ambient"),
                            ("lofi", "Lo-Fi"),
                            ("trap", "Trap"),
                            ("drill", "Drill"),
                            ("afrobeats", "Afrobeats"),
                            ("other", "Other"),
                        ],
                        help_text="Musical genre this template is designed for",
                        max_length=20,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("vocals", "Vocals"),
                            ("guitar", "Guitar"),
                            ("bass", "Bass"),
                            ("drums", "Drums"),
                            ("piano", "Piano"),
                            ("synth", "Synthesizer"),
                            ("keys", "Keys"),
                            ("saxophone", "Saxophone"),
                            ("percussion", "Percussion"),
                            ("pad", "Pad"),
                            ("full_mix", "Full Mix"),
                            ("hi_hats", "Hi-Hats"),
                            ("other", "Other"),
                        ],
                        help_text="Type of audio source this template works best with",
                        max_length=20,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("factory", "Factory Preset"),
                            ("user", "User Created"),
                            ("community", "Community Shared"),
                            ("imported", "Imported"),
                        ],
                        default="user",
                        help_text="Origin of this template (factory, user-created, community shared, or imported)",
                        max_length=20,
                    ),
                ),
                (
                    "fx_chain",
                    models.JSONField(
                        help_text="Array of FX plugin names in processing order"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Optional parameter settings for each FX (future feature)",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow other users to see and use this template",
                    ),
                ),
                (
                    "downloads",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used by other users",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0, help_text="Average user rating (0.0 to 5.0 stars)"
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of users who have rated this template",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for searching",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "files_processed",
                    models.IntegerField(
                        default=0, help_text="Number of files user tried to import"
                    ),
                ),
                (
                    "successful_imports",
                    models.IntegerField(
                        default=0,
                        help_text="Number of files successfully converted and imported",
                    ),
                ),
                (
                    "failed_imports",
                    models.IntegerField(
                        default=0, help_text="Number of files that failed to import"
                    ),
                ),
                (
                    "file_types",
                    models.JSONField(
                        default=list, help_text="Types of files that were imported"
                    ),
                ),
                (
                    "error_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Error messages from failed imports",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this import",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 stars"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, help_text="Optional written review"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="recommendations.fxchaintemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who gave this rating",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "template")},
            },
        ),
        migrations.CreateModel(
            name="TemplateCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this collection", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this collection"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow other users to see this collection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "templates",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Templates included in this collection",
                        to="recommendations.fxchaintemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this collection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="fxchaintemplate",
            index=models.Index(
                fields=["genre", "instrument_type"], name="recommendat_genre_1edd14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fxchaintemplate",
            index=models.Index(
                fields=["is_public", "rating"], name="recommendat_is_publ_ac5c15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fxchaintemplate",
            index=models.Index(
                fields=["template_type"], name="recommendat_templat_cdd455_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fxchaintemplate",
            unique_together={("user", "name")},
        ),
    ]
