# Generated by Django 4.2.23 on 2025-06-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presets",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preset",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
